version: "3.3"
services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.db
    hostname: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"

  api-users:
    image: code7unner/api-users:latest
    build:
      context: users
      dockerfile: Dockerfile
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: test_db
    ports:
      - "8080:8080"
    depends_on:
      - db

  api-todos:
    image: code7unner/api-todos:latest
    build:
      context: todos
      dockerfile: Dockerfile
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: test_db
    ports:
      - "8081:8081"
    depends_on:
      - db